version: "3.9" # optional since v1.27.0
services:
  server:
    container_name: Vms-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - my_data:/app/images
      - sqlite_data:/app/gorm
   


volumes:
  my_data:
  sqlite_data:

